const ORDER_STATUS = {
  PENDING: 'pending',
  CONFIRMED: 'confirmed',
  CANCELLED: 'cancelled',
  PAID: 'paid',
  FAILED: 'failed',
  COMPLETED: 'completed',
};

const VALID_TRANSITIONS = {
  [ORDER_STATUS.PENDING]: [ORDER_STATUS.CONFIRMED, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.CONFIRMED]: [ORDER_STATUS.PAID, ORDER_STATUS.FAILED],
  [ORDER_STATUS.PAID]: [ORDER_STATUS.COMPLETED],
  [ORDER_STATUS.CANCELLED]: [],
  [ORDER_STATUS.FAILED]: [],
  [ORDER_STATUS.COMPLETED]: [],
};

const EVENTS = {
  ORDER_CREATED: 'order.created',
  PAYMENT_COMPLETED: 'payment.completed',
};

const ERROR_CODES = {
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
};

const PAYMENT_FAILURE_THRESHOLD = 999.99;

module.exports = {
  ORDER_STATUS,
  VALID_TRANSITIONS,
  EVENTS,
  ERROR_CODES,
  PAYMENT_FAILURE_THRESHOLD,
};
